flair_defaults_types = [
    "bankflair",
    "dex-complete",
    "tapubulu-medal",
    "pikacup",
    "tapufini-medal",
    "ovalcharm",
    "shinycharm",
    "aloladex-complete"
]

flair_defaults = {
    "kwwxis": "bankflair",
    "JakeDubleyew": "bankflair",
    "_Toxicant_": "bankflair",
    "jmak456": "bankflair",
    "QQoL": "bankflair",
    "The__Linker": "bankflair",
    "Neon_Jon": "bankflair",
    "Estew02": "bankflair",
    "Porygon24": "bankflair",
    "SuperSmash007": "bankflair",
    "mrhi21": "bankflair",
    "RoPr-Crusader": "bankflair",
    "Ethanlac": "bankflair",
    "TootyPirate": "bankflair",
    "The_Ultra_Nerd": "bankflair",
    "DragonKnight147": "bankflair",
    "0verlord_Laharl": "bankflair",
    "creyk": "bankflair",
    "134Vaporeon": "bankflair",
    "DOG124579": "bankflair",
    "SgvSth": "bankflair",
    "Dont_be_offended_but": "bankflair",
    "AquaAura_": "bankflair",
    "Clasitav": "bankflair",
    #"Jovanang": "bankflair",
    "silverfingold": "bankflair",
    "MadDog1751": "bankflair",
    "supercalu": "bankflair",
    "AvatarJacob": "bankflair",
    "NutellaTheBear": "bankflair",
    "awesome58d": "bankflair",
    "lucariomaster2": "bankflair",
    "MesopotamianRex": "bankflair",
    "Navero": "bankflair",
    "FlounderR42": "bankflair",
    "CamNZ123": "bankflair",
    "Appare": "bankflair",
    "Fanboy8947": "bankflair",
    "KageyKay": "bankflair",
    "Ultimate_Souffle": "bankflair",
    "Herokra": "bankflair",
    "epicsmiley14": "bankflair",
    "DeasHer": "bankflair",
    "avodrok": "bankflair",
    "sufjanyorke": "bankflair",
    "TheLoyalTheorist": "bankflair",
    "thomas22088": "bankflair",
    "Achiever579": "bankflair",
    "PmMeYourTummy": "bankflair",
    "abitesizedtaco": "bankflair",
    "Arracor": "bankflair",
    "mrYT_DarkDeath": "bankflair",
    "iceytoa1": "bankflair",
    #"Monktoken": "bankflair",
    "llantarynboy": "bankflair",
    "EverettSeahawk": "bankflair",
    "Pikamilk": "bankflair",
    "Jonathanbrookly": "bankflair",
    "SleepyBojazzles": "bankflair",
    "AshKetchum48": "bankflair",
    "MegaMissingno": "bankflair",
    "jldixon1": "bankflair",
    "NEEEEEEEEEEERD": "bankflair",
    "-GoIden": "bankflair",
    "BLTmunch": "bankflair",
    "advantagefox": "bankflair",
    "LazarZwampertz": "bankflair",
    "Abrohmtoofar": "bankflair",
    "RomanticPanic": "bankflair",
    "Divinity4MAD": "bankflair",
    "PenMoney": "bankflair",
    "snaker1128": "bankflair",
    "TheWaterMiner": "bankflair",
    "Ciretako": "bankflair",
    "Jakeremix": "bankflair",
    "stevolime": "bankflair",
    "Carlyhu": "bankflair",
    "ThePanchamBros": "bankflair",
    "DaPandaGod": "bankflair",
    "cuddleskunk": "bankflair",
    "MayorPufnstuf": "bankflair",
    "Nejimus_Prime": "bankflair",
    "delbones": "bankflair",
    "DOMOHEAD": "bankflair",
    "ColdnessAwaits": "bankflair",
    "ultravictory": "bankflair",
    "ULTANOKA": "bankflair",
    "Scoutman2": "bankflair",
    "phoen91": "bankflair",
    #"Buntalufigus88": "bankflair",
    "sapper1775": "bankflair",
    "supercool898": "bankflair",
    "MangoTogo": "bankflair",
    "toodlebutts": "bankflair",
    "DanGaEb12": "bankflair",
    "StealthMH4U": "bankflair",
    "Genarel_Aggro": "bankflair",
    "Shadowkirby1234": "bankflair",
    "tylg": "bankflair",
    "Pandagami": "bankflair",
    "BunkerMonk716": "bankflair",
    "WafflesGaming": "bankflair",
    "Greeny78554": "bankflair",
    "Sir_Tortoise": "bankflair",
    "kfs520": "bankflair",
    "Kobazco": "bankflair",
    "Havocko": "bankflair",
    "zamorph": "bankflair",
    "DefiantEmpoleon": "bankflair",
    "Lennorz": "bankflair",
    "simmyruns": "bankflair",
    "raoul_d": "bankflair",
    "HyperBaka": "bankflair",
    "SeraviEdalborez": "bankflair",
    "ReconZ3X": "bankflair",
    "ThePolyglotLexicon": "bankflair",
    "ThaDennuz": "bankflair",
    "Wehavecookies56": "bankflair",
    "TheCowThatWentOink": "bankflair",
    "NiiGGZ": "bankflair",
    "Cheekything": "bankflair",
    "Sir-Tackington": "bankflair",
    "Netxus": "bankflair",
    "Coolcomment8": "bankflair",
    "vbolts": "bankflair",
    "Diet_Goomy": "bankflair",
    "FredChocoBear": "bankflair",
    "Alphaboy202": "bankflair",
    "TheDucksThatQuack": "bankflair",
    "XinTelnixSmite": "bankflair",
    "maxpwnez": "bankflair",
    "Rapid24": "bankflair",
    "flash2929": "bankflair",
    "Rayquaza3010": "bankflair",
    "cbright6062": "bankflair",
    "_StarFox69_": "bankflair",
    "MasonTheChef": "bankflair",
    "Ebola_Burrito": "bankflair",
    "Figusirow": "bankflair",
    "BionicleSM": "bankflair",
    "Brandilio": "bankflair",
    "Ayy_Johnny_J": "bankflair",
    "Truesarge": "bankflair",
    "Crono30067": "bankflair",
    "Kakuloo": "bankflair",
    "scriptlizard": "bankflair",
    "GodricMaelstrom": "bankflair",
    "BoltEyes": "bankflair",
    "celestialgem": "bankflair",
    "Cloud557": "bankflair",
    "manboy777": "bankflair",
    "KernoTheBoss": "bankflair",
    "chaz3121": "bankflair",
    "thunderblood": "bankflair",
    "Cedrico123": "bankflair",
    "DontDropThatPumpaRum": "bankflair",
    "iprizefighter": "bankflair",
    "Crimetarget": "bankflair",
    "PrisXiro": "bankflair",
    "FunGoblins": "bankflair",
    "The234sharingan": "bankflair",
    "itonokogiri": "bankflair",
    "Arenten": "bankflair",
    "APolarTurkey": "bankflair",
    "leboucher9": "bankflair",
    "PixellateRose": "bankflair",
    "CcHammer1764": "bankflair",
    "Kkrules": "bankflair",
    "Jomalo99": "bankflair",
    "ColinW0805": "bankflair",
    "SkyChu": "bankflair",
    "niewphonix": "bankflair",
    "Olympus131": "bankflair",
    "Eatbig-getbig": "bankflair",
    "Likthos": "bankflair",
    "Jamey4": "bankflair",
    "BreeZaps": "bankflair",
    "Munbalanced": "bankflair",
    "Aznmoonz": "bankflair",
    "QuinChunx": "bankflair",
    "BulleDeChagrin": "bankflair",
    "-Toey-": "bankflair",
    "Tetratonix": "bankflair",
    "wes2les": "bankflair",
    "IICooKiiEII": "bankflair",
    "CaptianDiscord": "bankflair",
    "TeamAquaAdminMatt": "bankflair",
    "Piotreshi": "bankflair",
    "NoaNate_": "bankflair",
    "6outof6": "bankflair",
    "IntricateSunlight": "bankflair",
    "cloudfightback": "bankflair",
    "MagicFighter": "bankflair",
    "PM_FEET_PLS_TY": "bankflair",
    "TheRealPdGaming": "bankflair",
    "Leo7Mario": "bankflair",
    "powergauge": "bankflair",
    "ken3": "bankflair",
    "Darkfire293": "bankflair",
    "PiplupParty": "bankflair",
    "zanaan01": "bankflair",
    "juanininfinity": "bankflair",
    "blackdemon500": "bankflair",
    "HydraTower": "bankflair",
    "fanananah": "bankflair",
    "Firstclassredhead": "bankflair",
    "Promanguy": "bankflair",
    "Struedelmuffin": "bankflair",
    "PalpatineSenpai": "bankflair",
    "Dabokbleef": "bankflair",
    "RealM3TA": "bankflair",
    "blukirbi": "bankflair",
    "Mudkipmakara": "bankflair",
    "Prohamen": "bankflair",
    "Hungry4Hats": "bankflair",
    "FetchingTheSwagni": "bankflair",
    "SlimeMush": "bankflair",
    "Fugishane": "bankflair",
    "Gohankuten": "bankflair",
    "Gunstling": "bankflair",
    "Underkiing": "bankflair",
    "MintyMinh": "bankflair",
    "rockoman100": "bankflair",
    "Wolpentiger": "bankflair",
    "piny18795": "bankflair",
    "SwedishSanta": "bankflair",
    "SurgeMaestro": "bankflair",
    "Chrushev": "bankflair",
    "chatsubobar": "bankflair",
    "olivesolives": "bankflair",
    "HatterTheSad": "bankflair",
    "M16_EPIC": "bankflair",
    "PM__ME__YOUR_NUDEZ": "bankflair",
    "KingPsych": "bankflair",
    "Mr_Biscuits_532": "bankflair",
    "partiallysplendid": "bankflair",
    "gamerguy369": "bankflair",
    "BandwagonBot": "bankflair",
    "Togder": "bankflair",
    "themolluskk": "bankflair",
    "Draeorc": "bankflair",
    "Spilcam": "bankflair",
    "cchris36": "bankflair",
    "chaobreaker": "bankflair",
    "Jonjon21428": "bankflair",
    "Zarrex": "bankflair",
    "Darkshadows9776": "bankflair",
    "SpatiallyRendering": "bankflair",
    "TheTrainBrain": "bankflair",
    "Mikerzoid": "bankflair",
    "Task_Set": "bankflair",
    "Kor3os": "bankflair",
    "Rusty1031": "bankflair",
    "XornMangar": "bankflair",
    "Vivec_lore": "bankflair",
    "Delta_ampharos": "bankflair",
    "ChaosNinjaZ": "bankflair",
    "Jeeves72": "bankflair",
    "MyNameIsDon": "bankflair",
    "Dragon789010": "bankflair",
    "Shuckster1": "bankflair",
    "Vorlent": "bankflair",
    "AttackOnTyrunt": "bankflair",
    "Duckaneer": "bankflair",
    "democratsgotnoclue": "bankflair",
    "SonSonecaTFB": "bankflair",
    "WillLoveLava": "bankflair",
    "RedditLocke": "bankflair",
    "iKickComputers": "bankflair",
    "okashiikessen": "bankflair",
    "ZXurai": "bankflair",
    "PsychoLunaticX": "bankflair",
    "flameguy21": "bankflair",
    "SacredxInsanity": "bankflair",
    "Grayoso": "bankflair",
    "Gnagsuaton": "bankflair",
    "mvoigt": "bankflair",
    "ghoststegosaur": "bankflair",
    "Metalhead62": "bankflair",
    "moodyssbm": "bankflair",
    "HaydnintheHaus": "bankflair",
    "infernape_party": "bankflair",
    "Appunator": "bankflair",
    "Aytri6": "bankflair",
    "thecball": "bankflair",
    "RSmeep13": "bankflair",
    "Iucario_is_life": "bankflair",
    "Wakstrom": "bankflair",
    "jengo3": "bankflair",
    "metallichris17": "bankflair",
    "iIIidAn": "bankflair",
    "bltdl": "bankflair",
    "TouchItAG": "bankflair",
    "AlexxxFio": "bankflair",
    "DailyMilkman": "bankflair",
    "TheOutWriter": "bankflair",
    "ethanb12007": "bankflair",
    "Jandepiel": "bankflair",
    "xSeizeHerSalad": "bankflair",
    "LewisMCYoutube": "bankflair",
    "coolanybody": "bankflair",
    "MisterOblivia": "bankflair",
    "analextremeteemo": "bankflair",
    "MrArcanine": "bankflair",
    "SahnicSp33d": "bankflair",
    "Wakareru": "bankflair",
    "Jochemwal": "bankflair",
    "kiohl": "bankflair",
    "LGBTreecko": "bankflair",
    "Tolstar": "bankflair",
    "Xtreme256": "bankflair",
    "RealDaMvp": "bankflair",
    "S-H-I-T": "bankflair",
    "gee0765": "bankflair",
    "Duder227": "bankflair",
    "FireRedCharizard": "bankflair",
    "KKSlider24": "bankflair",
    "Polkadot1017": "bankflair",
    "raven-jade": "bankflair",
    "TonyBotello31": "bankflair",
    "Cpod0": "bankflair",
    "EgeDal": "bankflair",
    "qqsseefftt": "bankflair",
    "unreal_croissant": "bankflair",
    "SOLIDBRAVO": "bankflair",
    "OmegaScorpio": "bankflair",
    "-TheFoolishJester": "bankflair",
    "Garmega": "bankflair",
    #"Lucas_One": "bankflair",
    "prs33": "bankflair",
    "CheesyChazzy": "bankflair",
    "Fabian_XYZ": "bankflair",
    "DylanG124": "bankflair",
    "hwc2313": "bankflair",
    "Scrubswarm": "bankflair",
    "Admins_Suck_Ass": "bankflair",
    "Cr4bmann": "bankflair",
    "HamsterCampster": "bankflair",
    "Superpat12": "bankflair",
    "nimpe": "bankflair",
    "spinakkus": "bankflair",
    "ButterLordEX": "bankflair",
    "basedrowlet": "bankflair",
    "PancakeWithSalt": "bankflair",
    "zeeeeeb": "bankflair",
    "hdubb": "bankflair",
    "quipstafishie": "bankflair",
    "Notapersonalname": "bankflair",
    "Hellopikachu9": "bankflair",
    "MagikarpFilet": "bankflair",
    "sonicstud": "bankflair",
    "Keyest": "bankflair",
    "rachabeth": "bankflair",
    "PM_ME_UR_EARTHPORN": "bankflair",
    "mymindstorm": "bankflair",
    "Beetle_knuckle": "bankflair",
    "ztc0611": "bankflair",
    "Kimhyunaa": "bankflair",
    "icycascades": "bankflair",
    "unknown_blitz": "bankflair",
    "xlerated": "bankflair",
    "orion_stellar": "bankflair",
    "YeezusShoe": "bankflair",
    "DragonKindle": "bankflair",
    "FezAndWand": "bankflair",
    "TriumphantBass": "bankflair",
    "BoneDryLXIX": "bankflair",
    "RobbieNewton": "bankflair",
    "SwitchbladeExplosion": "bankflair",
    
    "OwenQuillion": "tapubulu-medal",
    "Ocolyctpsis": "tapubulu-medal",
    "MarieSin": "tapubulu-medal",
    "HylianAngel": "tapubulu-medal",
    "Sushikitteh": "tapubulu-medal",
    "Monktoken": "tapubulu-medal",
    "Laradox": "tapubulu-medal",
    "Alinzko": "tapubulu-medal",
    "Bakatora34": "tapubulu-medal",
    "Healthy_Orange_Juice": "tapubulu-medal",
    "NoNameTheHarpy": "tapubulu-medal",
    "jAquaD": "tapubulu-medal",
    "alaserdolphin": "tapubulu-medal",
    "AtomicWalrus": "tapubulu-medal",
    "UW_Unknown_Warrior": "tapubulu-medal",
    "Snubbybill": "tapubulu-medal",
    #"Pokemoncutie": "tapubulu-medal",
    "pm_me_ur_river_otter": "tapubulu-medal",
    "Captain_Blue": "tapubulu-medal",
    "Buntalufigus88": "tapubulu-medal",
    "JonnyJinx": "tapubulu-medal",
    "Lumpoke": "tapubulu-medal",
    "s_10": "tapubulu-medal",
    "Matanui3": "tapubulu-medal",
    "TheGallagador": "tapubulu-medal",
    "dude071297": "tapubulu-medal",
    "Snaptah": "tapubulu-medal",
    "KuronixFirhyx": "tapubulu-medal",
    "Jovanang": "tapubulu-medal",
    "Draexzhan": "tapubulu-medal",
    "Zapdos678": "tapubulu-medal",
    "hiabara": "tapubulu-medal",
    "drewlase": "tapubulu-medal",
    "Tributyrin": "tapubulu-medal",
    "Rafat9": "tapubulu-medal",
    "Ackrylic": "tapubulu-medal",
    "kickwitkowskiass": "tapubulu-medal",
    "AwsumAndy": "tapubulu-medal",
    "dreams_of_mareep": "tapubulu-medal",
    "Tendedtadpole2": "tapubulu-medal",

    "ninmai700": "pikacup",
    "Shadowstar70712": "pikacup",
    "TrueLexatom": "pikacup",
    "Ascended_Orange": "pikacup",
    "TangleNathair": "pikacup",
    "Sotirisdim4": "pikacup",
    "Ookad": "pikacup",
    "fire-max": "pikacup",
    "ionchaser": "pikacup",
    "doge_apprentice": "pikacup",
    "FluffiestLeafeon": "pikacup",
    "KFCutman": "pikacup",
    "Cerderius": "pikacup",
    "KasaiGamma": "pikacup",
    "JustAnotherRandomLad": "pikacup",
    "WTFHaikus": "pikacup",
    "pokedude729": "pikacup",
    "Blubin_Boy": "pikacup",
    "Shadow_Kawazaki": "pikacup",
    "Dragon_Tamer166": "pikacup",
    "Leonys": "pikacup",
    "Crazydian": "pikacup",
    "Pokedude14": "pikacup",
    "Draycen": "pikacup",
    "Lucas_One": "pikacup",
    "SilverTris79": "pikacup",
    "MegaHyperDash": "pikacup",
    "TheDominantSoul": "pikacup",
    "Irni4Life": "pikacup",
    "DragonicOvrlord": "pikacup",
    "Nas160": "pikacup",
    "Menegoth": "pikacup",
    "Icalasari": "pikacup",
    "AntiFairySquad": "pikacup",
    
    "JustBanter_": "tapufini-medal",
    "Sisiwakanamaru": "tapufini-medal",
    "lawliet89": "tapufini-medal",
    "lucariojr": "tapufini-medal",
    "Healthy_Orange_Juice": "tapufini-medal",
    "bahilon": "tapufini-medal",
    "Mercerai": "tapufini-medal",
    "KDragon5": "tapufini-medal",
    "ApexGS": "tapufini-medal",
    "DSDark11": "tapufini-medal",
    "iGotUrCrayoIa": "tapufini-medal",
    "lupuscantus": "tapufini-medal",
    "ApatheticRadiance": "tapufini-medal",
    "phasmy": "tapufini-medal",
    "multisofteis": "tapufini-medal",
    "Kroctopus": "tapufini-medal",
    "Pokemoncutie": "tapufini-medal",
    "tehvik": "tapufini-medal",
    "Krisos35": "tapufini-medal",
    "MisirterE": "tapufini-medal",
    "Ardub23": "tapufini-medal",
    "Matanui3": "tapufini-medal",

    "OwenQuillion": "tapubulu-medal",
    "Ocolyctpsis": "tapubulu-medal",
    "MarieSin": "tapubulu-medal",
    "HylianAngel": "tapubulu-medal",
    "Sushikitteh": "tapubulu-medal",
    "Monktoken": "tapubulu-medal",
    "Laradox": "tapubulu-medal",
    "Alinzko": "tapubulu-medal",
    "Bakatora34": "tapubulu-medal",
    "Healthy_Orange_Juice": "tapubulu-medal",
    "NoNameTheHarpy": "tapubulu-medal",
    "jAquaD": "tapubulu-medal",
    "alaserdolphin": "tapubulu-medal",
    "AtomicWalrus": "tapubulu-medal",
    "UW_Unknown_Warrior": "tapubulu-medal",
    "Snubbybill": "tapubulu-medal",
    "Pokemoncutie": "tapubulu-medal",
    "pm_me_ur_river_otter": "tapubulu-medal",
    "Captain_Blue": "tapubulu-medal",
    "Buntalufigus88": "tapubulu-medal",
    "JonnyJinx": "tapubulu-medal",
    "Lumpoke": "tapubulu-medal",
    "s_10": "tapubulu-medal",
    "Matanui3": "tapubulu-medal",
    "TheGallagador": "tapubulu-medal",
    "dude071297": "tapubulu-medal",
    "Snaptah": "tapubulu-medal",
    "KuronixFirhyx": "tapubulu-medal",
    "Jovanang": "tapubulu-medal",
    "Draexzhan": "tapubulu-medal",
    "Zapdos678": "tapubulu-medal",
    "hiabara": "tapubulu-medal",
    "drewlase": "tapubulu-medal",
    "Tributyrin": "tapubulu-medal",
    "Rafat9": "tapubulu-medal",
    "Ackrylics": "tapubulu-medal",
    "kickwitkowskiass": "tapubulu-medal",
    "AwsumAndy": "tapubulu-medal",
    "dreams_of_mareep": "tapubulu-medal",
    "Tendedtadpole2": "tapubulu-medal",
    "Pikadex": "tapubulu-medal",
    "Will-TVR": "tapubulu-medal",
    "Awkward_Torkoal": "tapubulu-medal",

    "The_Little_Thingy": "aloladex-complete",
    "dhnova": "aloladex-complete",
    "SCRK16": "aloladex-complete",
    "AuroraFlareYT": "aloladex-complete",
    "Valencetalon": "aloladex-complete",
    "Ruckeysquad": "aloladex-complete",
    "Captain_Blue": "aloladex-complete",
    "Raptor_741": "aloladex-complete",
    "Raiinford": "aloladex-complete",
    "Megaswifter": "aloladex-complete",
    "technowalrus2712": "aloladex-complete",
    "Julian19500": "aloladex-complete",
    "Pokesaurus12": "aloladex-complete",
    "pronounced_it_wrong": "aloladex-complete",
    "xxSHAKEnBAKE11": "aloladex-complete",
    "AtomicWalrus": "aloladex-complete",
    "Symphawnics": "aloladex-complete",

    "erabel": "ovalcharm",
    "MercuryEnigma": "ovalcharm",
    "DrummuhDude": "ovalcharm",
    "Pikathepokepimp": "ovalcharm",
    "AldroVanda": "ovalcharm",
    "saltimmortalsea": "ovalcharm",
    "DoTheWave95": "ovalcharm",
    "gtetrakai": "ovalcharm",
    "Numelderp": "ovalcharm",

    "twitchy17": "shinycharm",
    "MaSalveh": "shinycharm",
    "Pikadex": "shinycharm",
    "RSN_Bran": "shinycharm",
    "Zeyq": "shinycharm",
    "PurpleTriangles": "shinycharm",
    "GleamingShield": "shinycharm",
    "FrankRizzoA": "shinycharm",
    "notyourpanda": "shinycharm",
    "AtomicWalrus": "shinycharm",
    "FrickFrickers": "shinycharm",
    "LorettaLecarde": "shinycharm",
    "CGoodlet26": "shinycharm",
    "EXGShadow": "shinycharm",
    "patjohbra": "shinycharm",
    "Marante": "shinycharm",
    "Riisso": "shinycharm",
    "LittleOKidd": "shinycharm",
    "theskipster00": "shinycharm",
    "margig32": "shinycharm",
    "Zeysir": "shinycharm",
    "HauntsYourProstate": "shinycharm",
    "Sorrica": "shinycharm",
    "anon14118": "shinycharm",
}

flair_trainers = [
    ('smtrainerflair', {
        1: [
            ('tf-sm1', 1, 'Ace Trainer - M'),
            ('tf-sm2', 1, 'Ace Trainer - F'),
            ('tf-sm3', 1, 'Beauty'),
            ('tf-sm4', 1, 'Backpacker - F'),
            ('tf-sm5', 1, 'Black Belt'),
            ('tf-sm6', 1, 'Bellhop (Butler)'),
            ('tf-sm7', 1, 'Collector'),
            ('tf-sm8', 2, 'Cook (Chef)'),
            ('tf-sm9', 1, 'Dancer - F'),
            ('tf-sm10', 1, 'Fisherman'),
            ('tf-sm11', 2, 'Gentleman'),
            ('tf-sm12', 1, 'Madame (Socialite)'),
            ('tf-sm13', 1, 'Hiker'),
            ('tf-sm14', 1, 'Janitor'),
            ('tf-sm15', 1, 'Lass'),
            ('tf-sm16', 1, 'Youngster'),
            ('tf-sm17', 1, 'Officer Worker (Clerk) - M'),
            ('tf-sm18', 1, 'Officer Worker (Clerk) - F'),
            ('tf-sm19', 1, 'Pokemon Breeder - M'),
            ('tf-sm20', 1, 'Pokemon Breeder - F'),
            ('tf-sm21', 1, 'Police Officer - M'),
            ('tf-sm22', 1, 'Preschooler - M'),
            ('tf-sm23', 1, 'Preschooler - F'),
            ('tf-sm24', 1, 'Punk - M'),
        ],
        2: [
            ('tf-sm25', 1, 'Punk - F'),
            ('tf-sm26', 1, 'Rising Star - M'),
            ('tf-sm27', 1, 'Rising Star - F'),
            ('tf-sm28', 1, 'Scientist - M'),
            ('tf-sm29', 1, 'Sightseer (Tourist) - M'),
            ('tf-sm30', 1, 'Sightseer (Tourist) - F'),
            ('tf-sm31', 1, 'Swimmer - M'),
            ('tf-sm32', 1, 'Swimmer - F'),
            ('tf-sm33', 1, 'Swimmer - F2'),
            ('tf-sm34', 1, 'Veteran - M'),
            ('tf-sm35', 1, 'Veteran - F'),
            ('tf-sm36', 1, 'Worker'),
            ('tf-sm37', 1, 'Nurse Joy (Alola)'),
            ('tf-sm38', 1, 'Firefighter'),
            ('tf-sm39', 1, 'Golfer - M'),
            ('tf-sm40', 1, 'Golfer - F'),
            ('tf-sm41', 1, 'Youth Athlete - M'),
            ('tf-sm42', 1, 'Youth Athlete - F'),
            ('tf-sm43', 1, 'Aether Foundation Employee - M'),
            ('tf-sm44', 1, 'Aether Foundation Employee - F'),
            ('tf-sm45', 1, 'Aether Foundation Employee - Genderless'),
            #('tf-sm46', 1, 'Aether Admin - Faba'),
            #('tf-sm47', 1, 'Aether Admin - Wicke'),
            #('tf-sm48', 1, 'Aether President - Lusamine'),
            #('tf-sm49', 1, 'The Masked Royal'),
            ('tf-sm46', 1, 'Team Skull Grunt - M'),
            ('tf-sm47', 1, 'Team Skull Grunt - F'),
            ('tf-sm48', 1, 'Pokemon Storage System Admin - Molayne'),
            ('tf-sm49', 1, 'Pokemon Storage System Admin - Bridgette'),
        ],
    }),
    ('xytrainerflair', {
        1: [
            ('tf-xy1', 1, 'Ace Trainer - M'),
            ('tf-xy2', 1, 'Ace Trainer - F'),
            ('tf-xy3', 2, 'Artist - M'),
            ('tf-xy4', 1, 'Artist - F'),
            ('tf-xy5', 2, 'Backpacker - M'),
            ('tf-xy6', 1, 'Beauty'),
            ('tf-xy7', 1, 'Black Belt'),
            ('tf-xy8', 1, 'Battle Girl'),
            ('tf-xy9', 1, 'Butler'),
            ('tf-xy10', 1, 'Maid'),
            ('tf-xy11', 2, 'Chef'),
            ('tf-xy12', 1, 'Fisherman'),
            ('tf-xy13', 2, 'Monsieur (Gentleman)'),
            ('tf-xy14', 1, 'Madame (Socialite)'),
            ('tf-xy15', 2, 'Hex Maniac'),
            ('tf-xy16', 2, 'Hiker'),
            ('tf-xy17', 1, 'Youngster'),
            ('tf-xy18', 1, 'Lass'),
            ('tf-xy19', 1, 'Rich Boy'),
            ('tf-xy20', 1, 'Lady'),
        ],
        2: [
            ('tf-xy21', 1, 'Pokemon Fan - M'),
            ('tf-xy22', 1, 'Pokemon Fan - F'),
            ('tf-xy23', 1, 'Pokemon Breeder - M'),
            ('tf-xy24', 1, 'Pokemon Breeder - F'),
            ('tf-xy25', 1, 'Pokemon Ranger - M'),
            ('tf-xy26', 1, 'Pokemon Ranger - F'),
            ('tf-xy27', 1, 'Preschooler - M'),
            ('tf-xy28', 1, 'Preschooler - F'),
            ('tf-xy29', 1, 'Psychic - M'),
            ('tf-xy30', 1, 'Punk - M'),
            ('tf-xy31', 1, 'Punk - F'),
            ('tf-xy32', 1, 'Rising Star - M'),
            ('tf-xy33', 1, 'Rising Star - F'),
            ('tf-xy34', 1, 'Schoolkid - M'),
            ('tf-xy35', 1, 'Schoolkid - F'),
            ('tf-xy36', 1, 'Scientist - M'),
            ('tf-xy37', 1, 'Scientist - F'),
            ('tf-xy38', 1, 'Tourist - M'),
            ('tf-xy39', 1, 'Tourist - F'),
            ('tf-xy40', 2, 'Tourist - F2'),
            ('tf-xy41', 1, 'Swimmer - M'),
            ('tf-xy42', 1, 'Swimmer - F'),
            ('tf-xy43', 1, 'Veteran - M'),
            ('tf-xy44', 1, 'Veteran - F'),
            ('tf-xy45', 1, 'Garcon (Waiter) - M'),
        ],
        3: [
            ('tf-xy46', 1, 'Waitress - F'),
            ('tf-xy47', 1, 'Worker - M'),
            ('tf-xy48', 1, 'Worker - M2'),
            ('tf-xy49', 1, 'Nurse Joy (Kalos)'),
            ('tf-xy50', 1, 'Fairy Tale Girl'),
            ('tf-xy51', 1, 'Furisode Girl - Pink'),
            ('tf-xy52', 1, 'Furisode Girl - Blue'),
            ('tf-xy53', 1, 'Furisode Girl - Black'),
            ('tf-xy54', 1, 'Furisode Girl - Beige'),
            ('tf-xy55', 1, 'Gardener'),
            ('tf-xy56', 1, 'Owner'),
            ('tf-xy57', 1, 'Roller Skater - M'),
            ('tf-xy58', 1, 'Roller Skater - F'),
            ('tf-xy59', 1, 'Sky Trainer - M'),
            ('tf-xy60', 1, 'Sky Trainer - F'),
            ('tf-xy61', 1, 'Battle Chatelaine - Nita'),
            ('tf-xy62', 1, 'Battle Chatelaine - Evelyn'),
            ('tf-xy63', 1, 'Battle Chatelaine - Dana'),
            ('tf-xy64', 1, 'Battle Chatelaine - Morgan'),
            ('tf-xy65', 1, 'Team Flare Grunt - M'),
            ('tf-xy66', 1, 'Team Flare Grunt - F'),
            ('tf-xy67', 1, 'Team Flare Admin - M'),
            ('tf-xy68', 1, 'Team Flare Admin - F'),
            #('tf-xy69', 1, 'Team Flare Boss - Lysander'),
            ('tf-xy69', 1, 'Photographer - Phil the Photo Guy'),
            #('tf-xy71', 1, 'Pokemon Trainer - AZ'),
        ],
    }),
    ('orastrainerflair', {
        1: [
            ('tf-oras1', 1, 'Ace Trainer - M'),
            ('tf-oras2', 1, 'Ace Trainer - F'),
            ('tf-oras3', 1, 'Aroma Lady'),
            ('tf-oras4', 1, 'Beauty'),
            ('tf-oras5', 1, 'Bird Keeper'),
            ('tf-oras6', 2, 'Battle Girl'),
            ('tf-oras7', 2, 'Bug Catcher'),
            ('tf-oras8', 1, 'Camper - M'),
            ('tf-oras9', 1, 'Picknicker - F'),
            ('tf-oras10', 1, 'Collector - M'),
            ('tf-oras11', 1, 'Fisherman'),
            ('tf-oras12', 1, 'Gentleman'),
            ('tf-oras13', 1, 'Guitarist - M'),
            ('tf-oras14', 2, 'Rich boy'),
            ('tf-oras15', 2, 'Lady'),
            ('tf-oras16', 1, 'Youngster'),
            ('tf-oras17', 1, 'Lass'),
            ('tf-oras18', 1, 'Ninja Boy'),
            ('tf-oras19', 2, 'Parasol Lady'),
            ('tf-oras20', 1, 'Pokemon Fan - M'),
            ('tf-oras21', 1, 'Pokemon Fan - F'),
        ],
        2: [
            ('tf-oras22', 1, 'Pokemon Maniac'),
            ('tf-oras23', 1, 'Pokemon Breeder - M'),
            ('tf-oras24', 1, 'Pokemon Breeder - F'),
            ('tf-oras25', 1, 'Pokemon Ranger - M'),
            ('tf-oras26', 1, 'Pokemon Ranger - F'),
            ('tf-oras27', 2, 'Street Thung (Punk) - M'),
            ('tf-oras28', 1, 'Street Thung (Punk) - F'),
            ('tf-oras29', 2, 'Rune Maniac'),
            ('tf-oras30', 2, 'Sailor'),
            ('tf-oras31', 1, 'Schoolkid - M'),
            ('tf-oras32', 1, 'Schoolkid - F'),
            ('tf-oras33', 1, 'Swimmer - F'),
            ('tf-oras34', 2, 'Tuber - M'),
            ('tf-oras35', 1, 'Tuber - F'),
            ('tf-oras36', 1, 'Expert (Veteran) - M'),
            ('tf-oras37', 1, 'Expert (Veteran)  - F'),
            ('tf-oras38', 1, 'Inverviewer - Gabby'),
            ('tf-oras39', 1, 'Inverviewer - TY'),
            ('tf-oras40', 2, 'Scuba Diver - M'),
            ('tf-oras41', 1, 'Free Diver - F'),
            ('tf-oras42', 1, 'Dragon Tamer - M'),
        ],
        3: [
            ('tf-oras43', 2, 'Bug Maniac - M'),
            ('tf-oras44', 2, 'Kindler - M'),
            ('tf-oras45', 1, 'Triathlete - Biker'),
            ('tf-oras46', 1, 'Triathlete - Jogger'),
            ('tf-oras47', 1, 'Triathlete - Swimmer'),
            ('tf-oras48', 2, 'Team Aqua Grunt - M'),
            ('tf-oras49', 1, 'Team Aqua Grunt - F'),
            ('tf-oras50', 1, 'Team Magma Grunt - M'),
            ('tf-oras51', 1, 'Team Magma Grunt - F'),
            ('tf-oras52', 2, 'Secret Base Expert - Aarune'),
            ('tf-oras53', 2, 'Pokemon Storage System Admin - Lanette'),
        ],
    }),
]

flair_etc = [
    ('formsflair', {
        1: [
            ('missingno',   False,  'Missingno'),
            ('130s',        True,   'Shiny Gyarados'),
            ('386a',        True,   'Deoxys Attack'),
            ('386d',        True,   'Deoxys Defense'),
            ('386s',        True,   'Deoxys Speed'),
            ('351a',        True,   'Snowy Castform'),
            ('351b',        True,   'Sunny Castform'),
            ('351c',        True,   'Rainy Castform'),
            ('421o',        True,   'Sunshine Cherrim'),
            ('422o',        True,   'East Sea Shellos'),
            ('423o',        True,   'East Sea Gastrodon'),
            ('479o',        False,  'AUTO'),
            ('479a',        True,   'Rotom-Frost'),
            ('479b',        True,   'Rotom-Heat'),
            ('479c',        True,   'Rotom-Mow'),
            ('479d',        True,   'Rotom-Fan'),
            ('479e',        True,   'Rotom-Wash'),
            ('487o',        True,   'Giratina-Origin'),
            ('492o',        True,   'Shaymin-Sky'),
            ('483p',        True,   'Primal Dialga'),
            ('550o',        True,   'Blue-Striped Basculin'),
            ('592f',        True,   'Female Frillish'),
            ('593f',        True,   'Female Jellicent'),
            ('647o',        True,   'Keldeo Resolute'),
            ('641o',        True,   'Tornadus-Therian'),
            ('642o',        True,   'Thundurus-Therian'),
            ('645o',        True,   'Landorus-Therian'),
            ('646b',        True,   'Kyurem Black'),
            ('646w',        True,   'Kyurem White'),
            ('648o',        True,   'Meloetta-Pirouette'),
            ('585a',        True,   'Autumn Form Deerling'),
            ('585s',        True,   'Summer Form Deerling'),
            ('585w',        True,   'Winter Form Deerling'),
        ],
        2: [
            ('586a',        True,   'Autumn Form Sawsbuck'),
            ('586s',        True,   'Summer Form Sawsbuck'),
            ('586w',        True,   'Winter Form Sawsbuck'),
            ('555o',        True,   'Zen Mode Darmanitan'),
            ('668f',        True,   'Female Pyroar'),
            ('678f',        True,   'Female Meowstic'),
            ('681o',        True,   'Aegislash Blade Forme'),
            ('25b',         True,   'Pikachu Belle'),
            ('25d',         True,   'Pikachu PhD'),
            ('25l',         True,   'Pikachu Libre'),
            ('25p',         True,   'Pikachu Pop Star'),
            ('25r',         True,   'Pikachu Rock Star'),
            ('666sp1',      True,   'Poké Ball Pattern Vivillon'),
            ('666a',        True,   'Modern Pattern Vivillon'),
            ('666b',        True,   'Archipelago Pattern Vivillon'),
            ('666c',        True,   'Elegant Pattern Vivillon'),
            ('666d',        True,   'Continental Pattern Vivillon'),
            ('666sp2',      True,   'Fancy Pattern Vivillon'),
            ('666e',        True,   'Garden Pattern Vivillon'),
            ('666f',        True,   'High Plains Pattern Vivillon'),
            ('666g',        True,   'Icy Snow Pattern Vivillon'),
            ('666h',        True,   'Jungle Pattern Vivillon'),
            ('666i',        True,   'Marine Pattern Vivillon'),
            ('666j',        True,   'Monsoon Pattern Vivillon'),
            ('666k',        True,   'Ocean Pattern Vivillon'),
            ('666l',        True,   'Polar Pattern Vivillon'),
            ('666m',        True,   'River Pattern Vivillon'),
            ('666n',        True,   'Sandstorm Pattern Vivillon'),
            ('666o',        True,   'Savanna Pattern Vivillon'),
            ('666p',        True,   'Sun Pattern Vivillon'),
            ('666q',        True,   'Tundra Pattern Vivillon'),
            ('669a',        True,   'Blue Flower Flabebe'),
            ('669b',        True,   'Orange Flower Flabebe'),
        ],
        3: [
            ('669c',        True,   'White Flower Flabebe'),
            ('669d',        True,   'Yellow Flower Flabebe'),
            ('670a',        True,   'Blue Flower Floette'),
            ('670b',        True,   'Orange Flower Floette'),
            ('670c',        True,   'White Flower Floette'),
            ('670d',        True,   'Yellow Flower Floette'),
            ('670e',        True,   'Eternal Floette'),
            ('671a',        True,   'Blue Flower Florges'),
            ('671b',        True,   'Orange Flower Florges'),
            ('671c',        True,   'White Flower Florges'),
            ('671d',        True,   'Yellow Flower Florges'),
            ('676a',        True,   'Dandy Trim Furfrou'),
            ('676b',        True,   'Debutante Trim Furfrou'),
            ('676c',        True,   'Diamond Trim Furfrou'),
            ('676d',        True,   'Heart Trim Furfrou'),
            ('676e',        True,   'Kabuki Trim Furfrou'),
            ('676f',        True,   'La Reine Trim Furfrou'),
            ('676g',        True,   'Matron Trim Furfrou'),
            ('676h',        True,   'Pharaoh Trim Furfrou'),
            ('676i',        True,   'Star Trim Furfrou'),
            ('720o',        True,   'Hoopa Unbound'),
            ('658ash',      True,   'Ash-Greninja'),
            ('718a',        True,   'Zygarde Core Forme'),
            ('718b',        True,   'Zygarde 10% Forme'),
            ('718c',        True,   'Zygarde Complete Forme'),
            ('741a',        True,   'Oricorio Pom-Pom Style'),
            ('741b',        True,   'Oricorio Pa\'u Style'),
            ('741c',        True,   'Oricorio Sensu Style'),
            ('745o',        True,   'Lycanroc Night Form'),
            ('746o',        True,   'Wishiwashi School Form'),
            ('774a',        True,   'Minior Green'),
            ('774b',        True,   'Minior Sky'),
            ('774c',        True,   'Minior Indigo'),
        ],
        4: [
            ('774d',        True,   'Minior Violet'),
            ('774e',        True,   'Minior Red'),
            ('774f',        True,   'Minior Orange'),
            ('774g',        True,   'Minior Yellow'),
            ('793o',        False,  'Magearna Original Form'),
            ('412a',        True,   'Burmy Trash Cloak'),
            ('412b',        True,   'Burmy Sandy Cloak'),
            ('413a',        True,   'Wormadam Trash Cloak'),
            ('413b',        True,   'Wormadam Sandy Cloak'),
        ],
        5: [
            ('a19',         True,   'AUTO'),
            ('a20',         True,   'AUTO'),
            ('a26',         True,   'AUTO'),
            ('a27',         True,   'AUTO'),
            ('a28',         True,   'AUTO'),
            ('a37',         True,   'AUTO'),
            ('a38',         True,   'AUTO'),
            ('a50',         True,   'AUTO'),
            ('a51',         True,   'AUTO'),
            ('a52',         True,   'AUTO'),
            ('a53',         True,   'AUTO'),
            ('a74',         True,   'AUTO'),
            ('a75',         True,   'AUTO'),
            ('a76',         True,   'AUTO'),
            ('a88',         True,   'AUTO'),
            ('a89',         True,   'AUTO'),
            ('a103',        True,   'AUTO'),
            ('a105',        True,   'AUTO'),
        ],
        6: [
            ('rb1',         True,   'Old School Rhydon'),
            ('rb2',         True,   'Old School Pidgeot'),
            ('rb3',         True,   'Old School Seel'),
            ('rb4',         True,   'Old School Clefairy'),
            ('rb5',         True,   'Old School Vileplume'),
            ('rb6',         True,   'Old School Beedrill'),
            ('rb7',         True,   'Old School Arbok'),
            ('rb8',         True,   'Old School Tauros'),
            ('rb9',         True,   'Old School Electrode'),
            ('rb10',        True,   'Old School Omanyte'),
            ('mystic',      True,   'Team Mystic'),
            ('instinct',    True,   'Team Instinct'),
            ('valor',       True,   'Team Valor'),
        ],
    }),
    ('megasflair', {
        1: [
            ('3m',          True,   'AUTO'),
            ('6xm',         True,   'AUTO'),
            ('6ym',         True,   'AUTO'),
            ('9m',          True,   'AUTO'),
            ('15m',         True,   'AUTO'),
            ('18m',         True,   'AUTO'),
            ('65m',         True,   'AUTO'),
            ('80m',         True,   'AUTO'),
            ('94m',         True,   'AUTO'),
            ('115m',        True,   'AUTO'),
            ('127m',        True,   'AUTO'),
            ('130m',        True,   'AUTO'),
            ('142m',        True,   'AUTO'),
            ('150xm',       True,   'AUTO'),
            ('150ym',       True,   'AUTO'),
            ('181m',        True,   'AUTO'),
            ('208m',        True,   'AUTO'),
            ('212m',        True,   'AUTO'),
            ('214m',        True,   'AUTO'),
            ('229m',        True,   'AUTO'),
            ('248m',        True,   'AUTO'),
            ('254m',        True,   'AUTO'),
            ('257m',        True,   'AUTO'),
            ('260m',        True,   'AUTO'),
            ('282m',        True,   'AUTO'),
            ('302m',        True,   'AUTO'),
            ('303m',        True,   'AUTO'),
            ('306m',        True,   'AUTO'),
            ('308m',        True,   'AUTO'),
            ('310m',        True,   'AUTO'),
            ('319m',        True,   'AUTO'),
            ('323m',        True,   'AUTO'),
            ('334m',        True,   'AUTO'),
        ],
        2: [
            ('354m',        True,   'AUTO'),
            ('359m',        True,   'AUTO'),
            ('362m',        True,   'AUTO'),
            ('373m',        True,   'AUTO'),
            ('376m',        True,   'AUTO'),
            ('380m',        True,   'AUTO'),
            ('381m',        True,   'AUTO'),
            ('382m',        True,   'Primal Kyogre'),
            ('383m',        True,   'Primal Groudon'),
            ('384m',        True,   'AUTO'),
            ('428m',        True,   'AUTO'),
            ('445m',        True,   'AUTO'),
            ('448m',        True,   'AUTO'),
            ('460m',        True,   'AUTO'),
            ('475m',        True,   'AUTO'),
            ('531m',        True,   'AUTO'),
            ('719m',        True,   'AUTO'),
        ],
    }),
    ('badgesflair', {
        1: [
            ('badge1',      True,   'Brock Badge'),
            ('badge2',      True,   'Misty Badge'),
            ('badge3',      True,   'Lt. Surge Badge'),
            ('badge4',      True,   'Erika Badge'),
            ('badge5',      True,   'Koga Badge'),
            ('badge6',      True,   'Sabrina Badge'),
            ('badge7',      True,   'Blaine Badge'),
            ('badge8',      True,   'Giovanni/Blue Badge'),
            ('badge9',      False,  ''),
            ('badge10',     False,  ''),
            ('badge11',     False,  ''),
            ('badge12',     False,  ''),
            ('badge13',     False,  ''),
            ('badge14',     False,  ''),
            ('badge15',     False,  ''),
            ('badge16',     False,  ''),
            ('badge17',     True,   'Team Rocket Emblem'),
            ('badge18',     False,  ''),
            ('badge19',     False,  ''),
            ('badge20',     False,  ''),
            ('badge21',     False,  ''),
            ('badge22',     False,  ''),
            ('badge23',     False,  ''),
            ('badge24',     False,  ''),
            ('badge25',     False,  ''),
            ('badge26',     False,  ''),
            ('badge27',     False,  ''),
            ('badge28',     False,  ''),
            ('badge29',     False,  ''),
            ('badge30',     False,  ''),
            ('badge31',     False,  ''),
            ('badge32',     False,  ''),
            ('badge33',     False,  ''),
        ],
        2: [
            ('badge34',     False,  ''),
            ('badge35',     False,  ''),
            ('badge36',     False,  ''),
            ('badge37',     False,  ''),
            ('badge38',     False,  ''),
            ('badge39',     False,  ''),
            ('badge40',     False,  ''),
            ('badge41',     False,  ''),
            ('badge42',     False,  ''),
            ('badge43',     False,  ''),
            ('badge44',     False,  ''),
            ('badge45',     False,  ''),
            ('badge46',     False,  ''),
            ('badge47',     False,  ''),
            ('badge48',     False,  ''),
            ('badge49',     False,  ''),
            ('badge50',     False,  ''),
            ('badge51',     False,  ''),
            ('badge52',     False,  ''),
            ('badge53',     False,  ''),
            ('badge54',     False,  ''),
            ('badge55',     False,  ''),
            ('badge56',     False,  ''),
            ('badge57',     True,   'Normalium-Z'),
            ('badge58',     True,   'Fightinium-Z'),
            ('badge59',     True,   'Waterium-Z'),
            ('badge60',     True,   'Firium-Z'),
            ('badge61',     True,   'Grassium-Z'),
            ('badge62',     True,   'Rockium-Z'),
            ('badge63',     True,   'Electrium-Z'),
            ('badge64',     True,   'Ghostium-Z'),
            ('badge65',     True,   'Darkinium-Z'),
            ('badge66',     True,   'Fairium-Z'),
        ],
        3: [
            ('badge67',     True,   'Groundium-Z'),
            ('badge68',     True,   'Dragonium-Z'),
            ('badge69',     True,   'Buginium-Z'),
            ('badge70',     True,   'Flyinium-Z'),
            ('badge71',     True,   'Steelium-Z'),
            ('badge72',     True,   'Icium-Z'),
            ('badge73',     True,   'Poisonium-Z'),
            ('badge74',     True,   'Psychium-Z'),
            ('badge75',     True,   'Team Skull Emblem'),
            ('badge76',     True,   'Aether Foundation Emblem'),
            ('badge77',     False,  ''),
            ('badge78',     False,  ''),
        ],
    }),
]

# create a flat list of ids in the flair_etc
flair_etc_list = []
for sheet_element in flair_etc:
    sheet_name = sheet_element[0]
    sheet_data = sheet_element[1]
    for line_number, sprite_map in sheet_data.items():
        for item in sprite_map:
            poke_id = item[0]
            flair_etc_list.append(poke_id)

flair_names = {
    # BEGIN STANDARD
    "1": ("Bulbasaur", True),
    "2": ("Ivysaur", True),
    "3": ("Venusaur", True),
    "4": ("Charmander", True),
    "5": ("Charmeleon", True),
    "6": ("Charizard", True),
    "7": ("Squirtle", True),
    "8": ("Wartortle", True),
    "9": ("Blastoise", True),
    "10": ("Caterpie", True),
    "11": ("Metapod", True),
    "12": ("Butterfree", True),
    "13": ("Weedle", True),
    "14": ("Kakuna", True),
    "15": ("Beedrill", True),
    "16": ("Pidgey", True),
    "17": ("Pidgeotto", True),
    "18": ("Pidgeot", True),
    "19": ("Rattata", True),
    "20": ("Raticate", True),
    "21": ("Spearow", True),
    "22": ("Fearow", True),
    "23": ("Ekans", True),
    "24": ("Arbok", True),
    "25": ("Pikachu", True),
    "26": ("Raichu", True),
    "27": ("Sandshrew", True),
    "28": ("Sandslash", True),
    "29": ("Nidoran-F", True),
    "30": ("Nidorina", True),
    "31": ("Nidoqueen", True),
    "32": ("Nidoran-M", True),
    "33": ("Nidorino", True),
    "34": ("Nidoking", True),
    "35": ("Clefairy", True),
    "36": ("Clefable", True),
    "37": ("Vulpix", True),
    "38": ("Ninetales", True),
    "39": ("Jigglypuff", True),
    "40": ("Wigglytuff", True),
    "41": ("Zubat", True),
    "42": ("Golbat", True),
    "43": ("Oddish", True),
    "44": ("Gloom", True),
    "45": ("Vileplume", True),
    "46": ("Paras", True),
    "47": ("Parasect", True),
    "48": ("Venonat", True),
    "49": ("Venomoth", True),
    "50": ("Diglett", True),
    "51": ("Dugtrio", True),
    "52": ("Meowth", True),
    "53": ("Persian", True),
    "54": ("Psyduck", True),
    "55": ("Golduck", True),
    "56": ("Mankey", True),
    "57": ("Primeape", True),
    "58": ("Growlithe", True),
    "59": ("Arcanine", True),
    "60": ("Poliwag", True),
    "61": ("Poliwhirl", True),
    "62": ("Poliwrath", True),
    "63": ("Abra", True),
    "64": ("Kadabra", True),
    "65": ("Alakazam", True),
    "66": ("Machop", True),
    "67": ("Machoke", True),
    "68": ("Machamp", True),
    "69": ("Bellsprout", True),
    "70": ("Weepinbell", True),
    "71": ("Victreebel", True),
    "72": ("Tentacool", True),
    "73": ("Tentacruel", True),
    "74": ("Geodude", True),
    "75": ("Graveler", True),
    "76": ("Golem", True),
    "77": ("Ponyta", True),
    "78": ("Rapidash", True),
    "79": ("Slowpoke", True),
    "80": ("Slowbro", True),
    "81": ("Magnemite", True),
    "82": ("Magneton", True),
    "83": ("Farfetch'd", True),
    "84": ("Doduo", True),
    "85": ("Dodrio", True),
    "86": ("Seel", True),
    "87": ("Dewgong", True),
    "88": ("Grimer", True),
    "89": ("Muk", True),
    "90": ("Shellder", True),
    "91": ("Cloyster", True),
    "92": ("Gastly", True),
    "93": ("Haunter", True),
    "94": ("Gengar", True),
    "95": ("Onix", True),
    "96": ("Drowzee", True),
    "97": ("Hypno", True),
    "98": ("Krabby", True),
    "99": ("Kingler", True),
    "100": ("Voltorb", True),
    "101": ("Electrode", True),
    "102": ("Exeggcute", True),
    "103": ("Exeggutor", True),
    "104": ("Cubone", True),
    "105": ("Marowak", True),
    "106": ("Hitmonlee", True),
    "107": ("Hitmonchan", True),
    "108": ("Lickitung", True),
    "109": ("Koffing", True),
    "110": ("Weezing", True),
    "111": ("Rhyhorn", True),
    "112": ("Rhydon", True),
    "113": ("Chansey", True),
    "114": ("Tangela", True),
    "115": ("Kangaskhan", True),
    "116": ("Horsea", True),
    "117": ("Seadra", True),
    "118": ("Goldeen", True),
    "119": ("Seaking", True),
    "120": ("Staryu", True),
    "121": ("Starmie", True),
    "122": ("Mr. Mime", True),
    "123": ("Scyther", True),
    "124": ("Jynx", True),
    "125": ("Electabuzz", True),
    "126": ("Magmar", True),
    "127": ("Pinsir", True),
    "128": ("Tauros", True),
    "129": ("Magikarp", True),
    "130": ("Gyarados", True),
    "131": ("Lapras", True),
    "132": ("Ditto", True),
    "133": ("Eevee", True),
    "134": ("Vaporeon", True),
    "135": ("Jolteon", True),
    "136": ("Flareon", True),
    "137": ("Porygon", True),
    "138": ("Omanyte", True),
    "139": ("Omastar", True),
    "140": ("Kabuto", True),
    "141": ("Kabutops", True),
    "142": ("Aerodactyl", True),
    "143": ("Snorlax", True),
    "144": ("Articuno", True),
    "145": ("Zapdos", True),
    "146": ("Moltres", True),
    "147": ("Dratini", True),
    "148": ("Dragonair", True),
    "149": ("Dragonite", True),
    "150": ("Mewtwo", True),
    "151": ("Mew", True),
    "152": ("Chikorita", True),
    "153": ("Bayleef", True),
    "154": ("Meganium", True),
    "155": ("Cyndaquil", True),
    "156": ("Quilava", True),
    "157": ("Typhlosion", True),
    "158": ("Totodile", True),
    "159": ("Croconaw", True),
    "160": ("Feraligatr", True),
    "161": ("Sentret", True),
    "162": ("Furret", True),
    "163": ("Hoothoot", True),
    "164": ("Noctowl", True),
    "165": ("Ledyba", True),
    "166": ("Ledian", True),
    "167": ("Spinarak", True),
    "168": ("Ariados", True),
    "169": ("Crobat", True),
    "170": ("Chinchou", True),
    "171": ("Lanturn", True),
    "172": ("Pichu", True),
    "173": ("Cleffa", True),
    "174": ("Igglybuff", True),
    "175": ("Togepi", True),
    "176": ("Togetic", True),
    "177": ("Natu", True),
    "178": ("Xatu", True),
    "179": ("Mareep", True),
    "180": ("Flaaffy", True),
    "181": ("Ampharos", True),
    "182": ("Bellossom", True),
    "183": ("Marill", True),
    "184": ("Azumarill", True),
    "185": ("Sudowoodo", True),
    "186": ("Politoed", True),
    "187": ("Hoppip", True),
    "188": ("Skiploom", True),
    "189": ("Jumpluff", True),
    "190": ("Aipom", True),
    "191": ("Sunkern", True),
    "192": ("Sunflora", True),
    "193": ("Yanma", True),
    "194": ("Wooper", True),
    "195": ("Quagsire", True),
    "196": ("Espeon", True),
    "197": ("Umbreon", True),
    "198": ("Murkrow", True),
    "199": ("Slowking", True),
    "200": ("Misdreavus", True),
    "201": ("Unown", True),
    "202": ("Wobbuffet", True),
    "203": ("Girafarig", True),
    "204": ("Pineco", True),
    "205": ("Forretress", True),
    "206": ("Dunsparce", True),
    "207": ("Gligar", True),
    "208": ("Steelix", True),
    "209": ("Snubbull", True),
    "210": ("Granbull", True),
    "211": ("Qwilfish", True),
    "212": ("Scizor", True),
    "213": ("Shuckle", True),
    "214": ("Heracross", True),
    "215": ("Sneasel", True),
    "216": ("Teddiursa", True),
    "217": ("Ursaring", True),
    "218": ("Slugma", True),
    "219": ("Magcargo", True),
    "220": ("Swinub", True),
    "221": ("Piloswine", True),
    "222": ("Corsola", True),
    "223": ("Remoraid", True),
    "224": ("Octillery", True),
    "225": ("Delibird", True),
    "226": ("Mantine", True),
    "227": ("Skarmory", True),
    "228": ("Houndour", True),
    "229": ("Houndoom", True),
    "230": ("Kingdra", True),
    "231": ("Phanpy", True),
    "232": ("Donphan", True),
    "233": ("Porygon2", True),
    "234": ("Stantler", True),
    "235": ("Smeargle", True),
    "236": ("Tyrogue", True),
    "237": ("Hitmontop", True),
    "238": ("Smoochum", True),
    "239": ("Elekid", True),
    "240": ("Magby", True),
    "241": ("Miltank", True),
    "242": ("Blissey", True),
    "243": ("Raikou", True),
    "244": ("Entei", True),
    "245": ("Suicune", True),
    "246": ("Larvitar", True),
    "247": ("Pupitar", True),
    "248": ("Tyranitar", True),
    "249": ("Lugia", True),
    "250": ("Ho-Oh", True),
    "251": ("Celebi", True),
    "252": ("Treecko", True),
    "253": ("Grovyle", True),
    "254": ("Sceptile", True),
    "255": ("Torchic", True),
    "256": ("Combusken", True),
    "257": ("Blaziken", True),
    "258": ("Mudkip", True),
    "259": ("Marshtomp", True),
    "260": ("Swampert", True),
    "261": ("Poochyena", True),
    "262": ("Mightyena", True),
    "263": ("Zigzagoon", True),
    "264": ("Linoone", True),
    "265": ("Wurmple", True),
    "266": ("Silcoon", True),
    "267": ("Beautifly", True),
    "268": ("Cascoon", True),
    "269": ("Dustox", True),
    "270": ("Lotad", True),
    "271": ("Lombre", True),
    "272": ("Ludicolo", True),
    "273": ("Seedot", True),
    "274": ("Nuzleaf", True),
    "275": ("Shiftry", True),
    "276": ("Taillow", True),
    "277": ("Swellow", True),
    "278": ("Wingull", True),
    "279": ("Pelipper", True),
    "280": ("Ralts", True),
    "281": ("Kirlia", True),
    "282": ("Gardevoir", True),
    "283": ("Surskit", True),
    "284": ("Masquerain", True),
    "285": ("Shroomish", True),
    "286": ("Breloom", True),
    "287": ("Slakoth", True),
    "288": ("Vigoroth", True),
    "289": ("Slaking", True),
    "290": ("Nincada", True),
    "291": ("Ninjask", True),
    "292": ("Shedinja", True),
    "293": ("Whismur", True),
    "294": ("Loudred", True),
    "295": ("Exploud", True),
    "296": ("Makuhita", True),
    "297": ("Hariyama", True),
    "298": ("Azurill", True),
    "299": ("Nosepass", True),
    "300": ("Skitty", True),
    "301": ("Delcatty", True),
    "302": ("Sableye", True),
    "303": ("Mawile", True),
    "304": ("Aron", True),
    "305": ("Lairon", True),
    "306": ("Aggron", True),
    "307": ("Meditite", True),
    "308": ("Medicham", True),
    "309": ("Electrike", True),
    "310": ("Manectric", True),
    "311": ("Plusle", True),
    "312": ("Minun", True),
    "313": ("Volbeat", True),
    "314": ("Illumise", True),
    "315": ("Roselia", True),
    "316": ("Gulpin", True),
    "317": ("Swalot", True),
    "318": ("Carvanha", True),
    "319": ("Sharpedo", True),
    "320": ("Wailmer", True),
    "321": ("Wailord", True),
    "322": ("Numel", True),
    "323": ("Camerupt", True),
    "324": ("Torkoal", True),
    "325": ("Spoink", True),
    "326": ("Grumpig", True),
    "327": ("Spinda", True),
    "328": ("Trapinch", True),
    "329": ("Vibrava", True),
    "330": ("Flygon", True),
    "331": ("Cacnea", True),
    "332": ("Cacturne", True),
    "333": ("Swablu", True),
    "334": ("Altaria", True),
    "335": ("Zangoose", True),
    "336": ("Seviper", True),
    "337": ("Lunatone", True),
    "338": ("Solrock", True),
    "339": ("Barboach", True),
    "340": ("Whiscash", True),
    "341": ("Corphish", True),
    "342": ("Crawdaunt", True),
    "343": ("Baltoy", True),
    "344": ("Claydol", True),
    "345": ("Lileep", True),
    "346": ("Cradily", True),
    "347": ("Anorith", True),
    "348": ("Armaldo", True),
    "349": ("Feebas", True),
    "350": ("Milotic", True),
    "351": ("Castform", True),
    "352": ("Kecleon", True),
    "353": ("Shuppet", True),
    "354": ("Banette", True),
    "355": ("Duskull", True),
    "356": ("Dusclops", True),
    "357": ("Tropius", True),
    "358": ("Chimecho", True),
    "359": ("Absol", True),
    "360": ("Wynaut", True),
    "361": ("Snorunt", True),
    "362": ("Glalie", True),
    "363": ("Spheal", True),
    "364": ("Sealeo", True),
    "365": ("Walrein", True),
    "366": ("Clamperl", True),
    "367": ("Huntail", True),
    "368": ("Gorebyss", True),
    "369": ("Relicanth", True),
    "370": ("Luvdisc", True),
    "371": ("Bagon", True),
    "372": ("Shelgon", True),
    "373": ("Salamence", True),
    "374": ("Beldum", True),
    "375": ("Metang", True),
    "376": ("Metagross", True),
    "377": ("Regirock", True),
    "378": ("Regice", True),
    "379": ("Registeel", True),
    "380": ("Latias", True),
    "381": ("Latios", True),
    "382": ("Kyogre", True),
    "383": ("Groudon", True),
    "384": ("Rayquaza", True),
    "385": ("Jirachi", True),
    "386": ("Deoxys", True),
    "387": ("Turtwig", True),
    "388": ("Grotle", True),
    "389": ("Torterra", True),
    "390": ("Chimchar", True),
    "391": ("Monferno", True),
    "392": ("Infernape", True),
    "393": ("Piplup", True),
    "394": ("Prinplup", True),
    "395": ("Empoleon", True),
    "396": ("Starly", True),
    "397": ("Staravia", True),
    "398": ("Staraptor", True),
    "399": ("Bidoof", True),
    "400": ("Bibarel", True),
    "401": ("Kricketot", True),
    "402": ("Kricketune", True),
    "403": ("Shinx", True),
    "404": ("Luxio", True),
    "405": ("Luxray", True),
    "406": ("Budew", True),
    "407": ("Roserade", True),
    "408": ("Cranidos", True),
    "409": ("Rampardos", True),
    "410": ("Shieldon", True),
    "411": ("Bastiodon", True),
    "412": ("Burmy Plant Cloak", True),
    "413": ("Wormadam PLant Cloak", True),
    "414": ("Mothim", True),
    "415": ("Combee", True),
    "416": ("Vespiquen", True),
    "417": ("Pachirisu", True),
    "418": ("Buizel", True),
    "419": ("Floatzel", True),
    "420": ("Cherubi", True),
    "421": ("Cherrim", True),
    "422": ("Shellos", True),
    "423": ("Gastrodon", True),
    "424": ("Ambipom", True),
    "425": ("Drifloon", True),
    "426": ("Drifblim", True),
    "427": ("Buneary", True),
    "428": ("Lopunny", True),
    "429": ("Mismagius", True),
    "430": ("Honchkrow", True),
    "431": ("Glameow", True),
    "432": ("Purugly", True),
    "433": ("Chingling", True),
    "434": ("Stunky", True),
    "435": ("Skuntank", True),
    "436": ("Bronzor", True),
    "437": ("Bronzong", True),
    "438": ("Bonsly", True),
    "439": ("Mime Jr.", True),
    "440": ("Happiny", True),
    "441": ("Chatot", True),
    "442": ("Spiritomb", True),
    "443": ("Gible", True),
    "444": ("Gabite", True),
    "445": ("Garchomp", True),
    "446": ("Munchlax", True),
    "447": ("Riolu", True),
    "448": ("Lucario", True),
    "449": ("Hippopotas", True),
    "450": ("Hippowdon", True),
    "451": ("Skorupi", True),
    "452": ("Drapion", True),
    "453": ("Croagunk", True),
    "454": ("Toxicroak", True),
    "455": ("Carnivine", True),
    "456": ("Finneon", True),
    "457": ("Lumineon", True),
    "458": ("Mantyke", True),
    "459": ("Snover", True),
    "460": ("Abomasnow", True),
    "461": ("Weavile", True),
    "462": ("Magnezone", True),
    "463": ("Lickilicky", True),
    "464": ("Rhyperior", True),
    "465": ("Tangrowth", True),
    "466": ("Electivire", True),
    "467": ("Magmortar", True),
    "468": ("Togekiss", True),
    "469": ("Yanmega", True),
    "470": ("Leafeon", True),
    "471": ("Glaceon", True),
    "472": ("Gliscor", True),
    "473": ("Mamoswine", True),
    "474": ("Porygon-Z", True),
    "475": ("Gallade", True),
    "476": ("Probopass", True),
    "477": ("Dusknoir", True),
    "478": ("Froslass", True),
    "479": ("Rotom", True),
    "480": ("Uxie", True),
    "481": ("Mesprit", True),
    "482": ("Azelf", True),
    "483": ("Dialga", True),
    "484": ("Palkia", True),
    "485": ("Heatran", True),
    "486": ("Regigigas", True),
    "487": ("Giratina", True),
    "488": ("Cresselia", True),
    "489": ("Phione", True),
    "490": ("Manaphy", True),
    "491": ("Darkrai", True),
    "492": ("Shaymin", True),
    "493": ("Arceus", True),
    "494": ("Victini", True),
    "495": ("Snivy", True),
    "496": ("Servine", True),
    "497": ("Serperior", True),
    "498": ("Tepig", True),
    "499": ("Pignite", True),
    "500": ("Emboar", True),
    "501": ("Oshawott", True),
    "502": ("Dewott", True),
    "503": ("Samurott", True),
    "504": ("Patrat", True),
    "505": ("Watchog", True),
    "506": ("Lillipup", True),
    "507": ("Herdier", True),
    "508": ("Stoutland", True),
    "509": ("Purrloin", True),
    "510": ("Liepard", True),
    "511": ("Pansage", True),
    "512": ("Simisage", True),
    "513": ("Pansear", True),
    "514": ("Simisear", True),
    "515": ("Panpour", True),
    "516": ("Simipour", True),
    "517": ("Munna", True),
    "518": ("Musharna", True),
    "519": ("Pidove", True),
    "520": ("Tranquill", True),
    "521": ("Unfezant", True),
    "522": ("Blitzle", True),
    "523": ("Zebstrika", True),
    "524": ("Roggenrola", True),
    "525": ("Boldore", True),
    "526": ("Gigalith", True),
    "527": ("Woobat", True),
    "528": ("Swoobat", True),
    "529": ("Drilbur", True),
    "530": ("Excadrill", True),
    "531": ("Audino", True),
    "532": ("Timburr", True),
    "533": ("Gurdurr", True),
    "534": ("Conkeldurr", True),
    "535": ("Tympole", True),
    "536": ("Palpitoad", True),
    "537": ("Seismitoad", True),
    "538": ("Throh", True),
    "539": ("Sawk", True),
    "540": ("Sewaddle", True),
    "541": ("Swadloon", True),
    "542": ("Leavanny", True),
    "543": ("Venipede", True),
    "544": ("Whirlipede", True),
    "545": ("Scolipede", True),
    "546": ("Cottonee", True),
    "547": ("Whimsicott", True),
    "548": ("Petilil", True),
    "549": ("Lilligant", True),
    "550": ("Basculin", True),
    "551": ("Sandile", True),
    "552": ("Krokorok", True),
    "553": ("Krookodile", True),
    "554": ("Darumaka", True),
    "555": ("Darmanitan", True),
    "556": ("Maractus", True),
    "557": ("Dwebble", True),
    "558": ("Crustle", True),
    "559": ("Scraggy", True),
    "560": ("Scrafty", True),
    "561": ("Sigilyph", True),
    "562": ("Yamask", True),
    "563": ("Cofagrigus", True),
    "564": ("Tirtouga", True),
    "565": ("Carracosta", True),
    "566": ("Archen", True),
    "567": ("Archeops", True),
    "568": ("Trubbish", True),
    "569": ("Garbodor", True),
    "570": ("Zorua", True),
    "571": ("Zoroark", True),
    "572": ("Minccino", True),
    "573": ("Cinccino", True),
    "574": ("Gothita", True),
    "575": ("Gothorita", True),
    "576": ("Gothitelle", True),
    "577": ("Solosis", True),
    "578": ("Duosion", True),
    "579": ("Reuniclus", True),
    "580": ("Ducklett", True),
    "581": ("Swanna", True),
    "582": ("Vanillite", True),
    "583": ("Vanillish", True),
    "584": ("Vanilluxe", True),
    "585": ("Deerling", True),
    "586": ("Sawsbuck", True),
    "587": ("Emolga", True),
    "588": ("Karrablast", True),
    "589": ("Escavalier", True),
    "590": ("Foongus", True),
    "591": ("Amoonguss", True),
    "592": ("Frillish", True),
    "593": ("Jellicent", True),
    "594": ("Alomomola", True),
    "595": ("Joltik", True),
    "596": ("Galvantula", True),
    "597": ("Ferroseed", True),
    "598": ("Ferrothorn", True),
    "599": ("Klink", True),
    "600": ("Klang", True),
    "601": ("Klinklang", True),
    "602": ("Tynamo", True),
    "603": ("Eelektrik", True),
    "604": ("Eelektross", True),
    "605": ("Elgyem", True),
    "606": ("Beheeyem", True),
    "607": ("Litwick", True),
    "608": ("Lampent", True),
    "609": ("Chandelure", True),
    "610": ("Axew", True),
    "611": ("Fraxure", True),
    "612": ("Haxorus", True),
    "613": ("Cubchoo", True),
    "614": ("Beartic", True),
    "615": ("Cryogonal", True),
    "616": ("Shelmet", True),
    "617": ("Accelgor", True),
    "618": ("Stunfisk", True),
    "619": ("Mienfoo", True),
    "620": ("Mienshao", True),
    "621": ("Druddigon", True),
    "622": ("Golett", True),
    "623": ("Golurk", True),
    "624": ("Pawniard", True),
    "625": ("Bisharp", True),
    "626": ("Bouffalant", True),
    "627": ("Rufflet", True),
    "628": ("Braviary", True),
    "629": ("Vullaby", True),
    "630": ("Mandibuzz", True),
    "631": ("Heatmor", True),
    "632": ("Durant", True),
    "633": ("Deino", True),
    "634": ("Zweilous", True),
    "635": ("Hydreigon", True),
    "636": ("Larvesta", True),
    "637": ("Volcarona", True),
    "638": ("Cobalion", True),
    "639": ("Terrakion", True),
    "640": ("Virizion", True),
    "641": ("Tornadus", True),
    "642": ("Thundurus", True),
    "643": ("Reshiram", True),
    "644": ("Zekrom", True),
    "645": ("Landorus", True),
    "646": ("Kyurem", True),
    "647": ("Keldeo", True),
    "648": ("Meloetta", True),
    "649": ("Genesect", True),
    "650": ("Chespin", True),
    "651": ("Quilladin", True),
    "652": ("Chesnaught", True),
    "653": ("Fennekin", True),
    "654": ("Braixen", True),
    "655": ("Delphox", True),
    "656": ("Froakie", True),
    "657": ("Frogadier", True),
    "658": ("Greninja", True),
    "659": ("Bunnelby", True),
    "660": ("Diggersby", True),
    "661": ("Fletchling", True),
    "662": ("Fletchinder", True),
    "663": ("Talonflame", True),
    "664": ("Scatterbug", True),
    "665": ("Spewpa", True),
    "666": ("Vivillon", True),
    "667": ("Litleo", True),
    "668": ("Pyroar", True),
    "669": ("Flabebe", True),
    "670": ("Floette", True),
    "671": ("Florges", True),
    "672": ("Skiddo", True),
    "673": ("Gogoat", True),
    "674": ("Pancham", True),
    "675": ("Pangoro", True),
    "676": ("Furfrou", True),
    "677": ("Espurr", True),
    "678": ("Meowstic", True),
    "679": ("Honedge", True),
    "680": ("Doublade", True),
    "681": ("Aegislash", True),
    "682": ("Spritzee", True),
    "683": ("Aromatisse", True),
    "684": ("Swirlix", True),
    "685": ("Slurpuff", True),
    "686": ("Inkay", True),
    "687": ("Malamar", True),
    "688": ("Binacle", True),
    "689": ("Barbaracle", True),
    "690": ("Skrelp", True),
    "691": ("Dragalge", True),
    "692": ("Clauncher", True),
    "693": ("Clawitzer", True),
    "694": ("Helioptile", True),
    "695": ("Heliolisk", True),
    "696": ("Tyrunt", True),
    "697": ("Tyrantrum", True),
    "698": ("Amaura", True),
    "699": ("Aurorus", True),
    "700": ("Sylveon", True),
    "701": ("Hawlucha", True),
    "702": ("Dedenne", True),
    "703": ("Carbink", True),
    "704": ("Goomy", True),
    "705": ("Sliggoo", True),
    "706": ("Goodra", True),
    "707": ("Klefki", True),
    "708": ("Phantump", True),
    "709": ("Trevenant", True),
    "710": ("Pumpkaboo", True),
    "711": ("Gourgeist", True),
    "712": ("Bergmite", True),
    "713": ("Avalugg", True),
    "714": ("Noibat", True),
    "715": ("Noivern", True),
    "716": ("Xerneas", True),
    "717": ("Yveltal", True),
    "718": ("Zygarde", True),
    "719": ("Diancie", True),
    "720": ("Hoopa", True),
    "721": ("Volcanion", True),
    # END STANDARD
    
    # BEGIN ALOLA
    "722": ("Rowlet", True),
    "723": ("Dartrix", True),
    "724": ("Decidueye", True),
    "725": ("Litten", True),
    "726": ("Torracat", True),
    "727": ("Incineroar", True),
    "728": ("Popplio", True),
    "729": ("Brionne", True),
    "730": ("Primarina", True),
    "731": ("Pikipek", True),
    "732": ("Trumbeak", True),
    "733": ("Toucannon", True),
    "734": ("Yungoos", True),
    "735": ("Gumshoos", True),
    "736": ("Grubbin", True),
    "737": ("Charjabug", True),
    "738": ("Vikavolt", True),
    "739": ("Crabrawler", True),
    "740": ("Crabominable", True),
    "741": ("Oricorio", True),
    "742": ("Cutiefly", True),
    "743": ("Ribombee", True),
    "744": ("Rockruff", True),
    "745": ("Lycanroc", True),
    "746": ("Wishiwashi", True),
    "747": ("Mareanie", True),
    "748": ("Toxapex", True),
    "749": ("Mudbray", True),
    "750": ("Mudsdale", True),
    "751": ("Dewpider", True),
    "752": ("Araquanid", True),
    "753": ("Fomantis", True),
    "754": ("Lurantis", True),
    "755": ("Morelull", True),
    "756": ("Shiinotic", True),
    "757": ("Salandit", True),
    "758": ("Salazzle", True),
    "759": ("Stufful", True),
    "760": ("Bewear", True),
    "761": ("Bounsweet", True),
    "762": ("Steenee", True),
    "763": ("Tsareena", True),
    "764": ("Comfey", True),
    "765": ("Oranguru", True),
    "766": ("Passimian", True),
    "767": ("Wimpod", True),
    "768": ("Golisopod", True),
    "769": ("Sandygast", True),
    "770": ("Pallosand", True),
    "771": ("Pyukumuku", True),
    "772": ("Type: Null", True),
    "773": ("Silvally", True),
    "774": ("Minior", True),
    "775": ("Komala", True),
    "776": ("Turtonator", True),
    "777": ("Togedemaru", True),
    "778": ("Mimikyu", True),
    "779": ("Bruxish", True),
    "780": ("Drampa", True),
    "781": ("Dhelmise", True),
    "782": ("Jangmo-o", True),
    "783": ("Hakamo-o", True),
    "784": ("Kommo-o", True),
    "785": ("Tapu Koko", True),
    "786": ("Tapu Lele", True),
    "787": ("Tapu Bulu", True),
    "788": ("Tapu Fini", True),
    "789": ("Cosmog", True),
    "790": ("Cosmoem", True),
    "791": ("Solgaleo", True),
    "792": ("Lunala", True),
    "793": ("UB-01 Symbiont - Nihilego", True),
    "794": ("UB-02 Absorption - Buzzwole", True),
    "795": ("UB-02 Beauty - Pheromosa", True),
    "796": ("UB-03 Lighting - Xurkitree", True),
    "797": ("UB-04 Blaster - Celesteela", True),
    "798": ("UB-04 Blade - Kartana", True),
    "799": ("UB-05 Glutton - Guzzlord", True),
    "800": ("Necrozma", True),
    "801": ("Magearna", True),
    "802": ("Marshadow", False),
    # END ALOLA
}